<a href="https://colab.research.google.com/github/chandanaka07-design/AI-laborartory/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# creating a array
arr_id = np.array([1,2,3,4,5])

print(arr_id)

[1 2 3 4 5]


In [ ]:
import numpy as np

#creating matrices directly using numpy
matrix_a = np.array([[10, 20], [30, 40]])
matrix_b = np.array([[5, 5], [10, 10]])

#matrix addition
addition = matrix_a + matrix_b

#matrix multiplication
elementwise_mult = matrix_a*matrix_b

#find max and min
max_val = np.max(matrix_a)
min_val = np.min(matrix_a)

print("addition:\n", addition)
print("multiplication:\n", elementwise_mult)
print("maximum in matrix a", max_val)
print("minimum in matrix a", min_val)

addition:
 [[15 25]
 [40 50]]
multiplication:
 [[ 50 100]
 [300 400]]
maximum in matrix a 40
minimum in matrix a 10
